apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.0
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/htmll"
        name: data
  volumes:
    - name: data
      
