apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    app: nginx-app
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/app-data
